version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python test_script.py